
console.log("Begin")
console.log("  is there a clean pot? no")
console.log("  clean a pot")
console.log("  load water")
console.log("  is there enough coffee? no")
console.log("  open a new bag of coffee")
console.log("  loading coffee ")
console.log("  putting on the burner ")
console.log("  setting burner to 4 ")
console.log("  waiting 15 minutes... ")
console.log("Done! ")
